'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const keys=new Set(), cheatKeys=['aim','esp','recoil','ammo'], cheatNames=['AIM','ESP','NO RECOIL','∞ AMMO'];
let ws=null,state=null,ids=[],map=[],mouse=0,fire=false,aim=false,oldPhase='',spectate=0,toastTimer,audio,closedByUser=false;
let options={sensitivity:1,volume:.25,quality:3};try{Object.assign(options,JSON.parse(localStorage.getItem('cheat-fps-options')||'{}'));}catch{}
const sounds=new Map(), gamepadButtons=new Map(), hitTimes=new Map();
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4000);}
function screen(name){for(const id of ['menu','lobby','playUI','result'])$(id).classList.toggle('hidden',id!==name);}
function send(data,id){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify({...data,id:id||ids[0]}));}
function sound(hit=false){if(!audio||options.volume<=0)return;const o=audio.createOscillator(),g=audio.createGain();o.type=hit?'sine':'sawtooth';o.frequency.setValueAtTime(hit?900:135,audio.currentTime);o.frequency.exponentialRampToValueAtTime(hit?450:40,audio.currentTime+.07);g.gain.setValueAtTime(options.volume*.10,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.09);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.1);}
function enableAudio(){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function connect(join){if(ws)ws.close();closedByUser=false;enableAudio();state=null;oldPhase='';sounds.clear();screen('menu');$('create').disabled=$('join').disabled=true;toast('서버에 연결 중…');const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws=socket;
socket.onopen=()=>socket.send(JSON.stringify({code:join?$('code').value.trim():'',mode:$('mode').value,name:$('name').value,split:$('split').checked}));
socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='welcome'){ids=d.ids;map=d.map;toast(`방 ${d.code} · 접속 완료`);}else if(d.type==='error')toast(d.message);else if(d.type==='state'){state=d;update();}};
socket.onerror=()=>toast('연결 실패. 서버 주소와 실행 상태를 확인해 주세요.');socket.onclose=()=>{if(ws!==socket)return;$('create').disabled=$('join').disabled=false;if(!closedByUser){toast('서버 연결이 종료되었다. 다시 방에 참가해 주세요.');screen('menu');}state=null;document.exitPointerLock?.();};}
$('create').onclick=()=>connect(false);$('join').onclick=()=>{if($('code').value.trim())connect(true);else toast('방 코드를 입력해 주세요.');};
function leave(){closedByUser=true;ws?.close();ws=null;state=null;keys.clear();fire=aim=false;document.exitPointerLock?.();$('settings').close();$('create').disabled=$('join').disabled=false;screen('menu');}
document.querySelectorAll('.leave').forEach(b=>b.onclick=leave);
$('exit').onclick=()=>{leave();toast('게임을 종료했다. 브라우저 탭을 닫으면 된다.');};
function settings(){keys.clear();fire=aim=false;document.exitPointerLock?.();for(const k of ['sensitivity','volume','quality'])$(k).value=options[k];$('settings').showModal();}
$('settingsOpen').onclick=$('pause').onclick=settings;
$('settingsClose').onclick=()=>{$('settings').close();};
for(const k of ['sensitivity','volume','quality'])$(k).oninput=()=>{options[k]=Number($(k).value);try{localStorage.setItem('cheat-fps-options',JSON.stringify(options));}catch{}};
$('start').onclick=()=>send({type:'start'});$('again').onclick=()=>send({type:'lobby'});
function toggles(p){return cheatKeys.map((k,i)=>`<button class="${p.cheats[k]?'on':''}" data-toggle="${k}" data-id="${p.id}">${cheatNames[i]}</button>`).join('');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-toggle]');if(b)send({type:'toggle',key:b.dataset.toggle},b.dataset.id);});
let lobbyStamp='',cheatStamp='';
function update(){const d=state;const phase=d.state;if(phase!==oldPhase){oldPhase=phase;screen(phase==='LOBBY'?'lobby':phase==='MATCH_END'?'result':'playUI');if(phase==='LOBBY'){lobbyStamp='';document.exitPointerLock?.();}if(phase==='MATCH_END'){document.exitPointerLock?.();results();}keys.clear();fire=aim=false;}
if(phase==='LOBBY'){
 $('roomCode').textContent=d.code;$('modeInfo').textContent=d.mode==='ai'?'AI전 · 아군 빈자리는 AI가 채운다. 모든 AI는 치트 미사용.':'로컬 대전 · 6명 준비 후 시작. 다른 기기에서 같은 주소와 방 코드를 사용한다.';
 $('roster').innerHTML=[0,1].map(t=>`<div class="card ${t?'red':'blue'}"><h3>${t?'RED':'BLUE'} / ${d.players.filter(p=>p.team===t).length} OF 3</h3>${d.players.filter(p=>p.team===t).map(p=>`<div class="member"><span>${escapeHTML(p.name)} ${p.id===d.host?'♛':''}</span><span>${p.ready?'준비 완료':'편성 중'}</span></div>`).join('')}</div>`).join('');
 const stamp=JSON.stringify(d.players.filter(p=>ids.includes(p.id)).map(p=>[p.id,p.ready,p.team,p.skin,p.cheats]));
 if(stamp!==lobbyStamp&&!($('custom').contains(document.activeElement)&&['INPUT','SELECT'].includes(document.activeElement.tagName))){lobbyStamp=stamp;$('custom').innerHTML=ids.map((id,i)=>{const p=d.players.find(p=>p.id===id);if(!p)return '';return `<div class="card"><h3>PLAYER ${i+1}</h3><label>콜사인<input data-name="${id}" value="${escapeHTML(p.name)}" maxlength="16"></label><label>캐릭터<select data-skin="${id}">${['scout','warden','rogue'].map(s=>`<option ${p.skin===s?'selected':''}>${s}</option>`).join('')}</select></label><label>팀<select data-team="${id}" ${d.mode==='ai'?'disabled':''}><option value="0" ${p.team===0?'selected':''}>BLUE</option><option value="1" ${p.team===1?'selected':''}>RED</option></select></label><div class="toggles">${toggles(p)}</div><button data-ready="${id}" class="${p.ready?'on':''}">${p.ready?'준비 취소':'준비 완료'}</button></div>`;}).join('');}
 $('start').disabled=!ids.includes(d.host);$('controlsInfo').textContent='모든 참가자가 준비한 뒤 방장이 시작한다. 조작 방법은 메인 메뉴의 설정에서 확인할 수 있다.';
}
const nextCheatStamp=JSON.stringify(d.players.filter(p=>ids.includes(p.id)).map(p=>[p.id,p.cheats]));
if(nextCheatStamp!==cheatStamp){cheatStamp=nextCheatStamp;$('cheatControls').innerHTML=ids.map((id,i)=>{const p=d.players.find(p=>p.id===id);return p?`<div class="toggles"><span>P${i+1}</span>${toggles(p)}</div>`:'';}).join('');}
for(const p of d.players){const old=sounds.get(p.id);if(old&&p.shots>old.shots&&ids.includes(p.id))sound();if(old&&p.hit>old.hit&&ids.includes(p.id)){sound(true);hitTimes.set(p.id,performance.now());}sounds.set(p.id,{shots:p.shots,hit:p.hit});}
}
$('custom').addEventListener('change',e=>{const el=e.target;const id=el.dataset.name||el.dataset.skin||el.dataset.team;if(!id)return;const card=el.closest('.card');send({type:'custom',name:card.querySelector('input').value,skin:card.querySelector('[data-skin]').value,team:Number(card.querySelector('[data-team]').value)},id);});
$('custom').addEventListener('click',e=>{if(e.target.dataset.ready)send({type:'ready'},e.target.dataset.ready);});
function results(){const d=state;$('resultTitle').textContent=`${d.score[0]>d.score[1]?'BLUE':'RED'} TEAM VICTORY`;$('finalScore').textContent=d.score.join(' : ');$('rounds').innerHTML=d.history.map(h=>`<span>R${h.round} · ${h.winner?'RED':'BLUE'}<br><small>${escapeHTML(h.reason)}</small></span>`).join('');$('stats').innerHTML='<table><thead><tr><th>플레이어</th><th>팀</th><th>킬</th><th>데스</th></tr></thead><tbody>'+d.players.map(p=>`<tr><td>${escapeHTML(p.name)}</td><td>${p.team?'RED':'BLUE'}</td><td>${p.kills}</td><td>${p.deaths}</td></tr>`).join('')+'</tbody></table>';$('again').disabled=!ids.includes(d.host);}
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(e.code==='Escape'){if(!$('settings').open&&state&&state.state!=='LOBBY')settings();return;}if($('settings').open)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat){let i=['Digit1','Digit2','Digit3','Digit4'].indexOf(e.code);if(i>=0)send({type:'toggle',key:cheatKeys[i]});i=['Digit7','Digit8','Digit9','Digit0'].indexOf(e.code);if(i>=0&&ids[1])send({type:'toggle',key:cheatKeys[i]},ids[1]);if(e.code==='KeyV')spectate++;}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();fire=aim=false;mouse=0;});
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{enableAudio();if(!state)return;if(e.pointerType==='mouse'){if(!document.pointerLockElement&&canvas.requestPointerLock){try{const p=canvas.requestPointerLock();p?.catch(()=>{});}catch{}}if(e.button===0)fire=true;if(e.button===2)aim=true;}};
window.addEventListener('pointerup',e=>{if(e.button===0)fire=false;if(e.button===2)aim=false;});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas)mouse+=e.movementX*.0025*options.sensitivity;});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);enableAudio();};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});
let touchX=0;$('lookZone').onpointerdown=e=>{touchX=e.clientX;e.target.setPointerCapture(e.pointerId);};$('lookZone').onpointermove=e=>{if(e.buttons){mouse+=(e.clientX-touchX)*.005*options.sensitivity;touchX=e.clientX;}};
function down(k){return keys.has(k)?1:0;}
setInterval(()=>{if(!state)return;const pads=navigator.getGamepads?Array.from(navigator.getGamepads()).filter(Boolean):[];ids.forEach((id,i)=>{let f=i?down('ArrowUp')-down('ArrowDown'):down('KeyW')-down('KeyS'),s=i?down('ArrowRight')-down('ArrowLeft'):down('KeyD')-down('KeyA'),turn=i?down('KeyL')-down('KeyJ'):down('KeyE')-down('KeyQ')+mouse/(3.2/30),shoot=i?!!down('Enter'):fire||!!down('Space'),ads=i?!!down('ShiftRight'):aim||!!down('ShiftLeft'),reload=!!down(i?'KeyP':'KeyR');const pad=pads[i];if(pad){const dead=v=>Math.abs(v)>.16?v:0;f-=dead(pad.axes[1]||0);s+=dead(pad.axes[0]||0);turn+=dead(pad.axes[2]||0);shoot ||=pad.buttons[7]?.pressed;ads ||=pad.buttons[6]?.pressed;reload ||=pad.buttons[0]?.pressed;[12,13,14,15].forEach((b,j)=>{const key=`${i}:${b}`,pressed=pad.buttons[b]?.pressed;if(pressed&&!gamepadButtons.get(key))send({type:'toggle',key:cheatKeys[j]},id);gamepadButtons.set(key,pressed);});}if($('settings').open){f=s=turn=0;shoot=ads=reload=false;}send({type:'input',f,s,turn,fire:!!shoot,aim:!!ads,reload:!!reload},id);});mouse=0;},1000/30);
function wall(x,y){return !map[Math.floor(y)]||map[Math.floor(y)][Math.floor(x)]!=='0';}
function ray(x,y,a){const dx=Math.cos(a),dy=Math.sin(a);let mx=Math.floor(x),my=Math.floor(y);const ddx=Math.abs(1/dx),ddy=Math.abs(1/dy),sx=dx<0?-1:1,sy=dy<0?-1:1;let tx=(dx<0?x-mx:mx+1-x)*ddx,ty=(dy<0?y-my:my+1-y)*ddy,side=0;for(let i=0;i<80;i++){if(tx<ty){tx+=ddx;mx+=sx;side=0;}else{ty+=ddy;my+=sy;side=1;}if(wall(mx+.5,my+.5))break;}return {d:Math.max(.03,side?ty-ddy:tx-ddx),side,mx,my};}
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
function text(s,x,y,size=14,color='#e7f1ed',align='left'){ctx.font=`bold ${size}px Arial`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(s,x,y);ctx.textAlign='left';}
function renderView(player,x,y,w,h,index){ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.translate(x,y);let p=player;const dead=player.hp<=0;if(dead){const mates=state.players.filter(q=>q.team===player.team&&q.hp>0);p=mates[spectate%Math.max(1,mates.length)]||player;}
const fov=aim&&index===0?.85:1.12,proj=w/(2*Math.tan(fov/2)),horizon=h*.47+p.kick*h*.15;
const sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#080e16');sky.addColorStop(1,'#293c43');ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon);const floor=ctx.createLinearGradient(0,horizon,0,h);floor.addColorStop(0,'#17272b');floor.addColorStop(1,'#35433d');ctx.fillStyle=floor;ctx.fillRect(0,horizon,w,h-horizon);
const step=Number(options.quality)||3,z=[];
for(let col=0;col<w;col+=step){const offset=Math.atan((col-w/2)/proj),r=ray(p.x,p.y,p.yaw+offset),dist=r.d*Math.cos(offset);for(let j=0;j<step;j++)z[col+j]=dist;const hh=proj/dist;const shade=Math.max(.16,1-dist/23)*(r.side?.72:1);const accent=(r.mx===9||r.mx===10)?[110,132,81]:[94,124,131];ctx.fillStyle=`rgb(${accent.map(c=>Math.floor(c*shade)).join(',')})`;ctx.fillRect(col,horizon-hh/2,step+1,hh);ctx.fillStyle=`rgba(198,255,71,${shade*.55})`;ctx.fillRect(col,horizon-hh*.34,step+1,Math.max(1,hh*.035));ctx.fillStyle='#0003';ctx.fillRect(col,horizon+hh*.45,step+1,hh*.05);}
const others=state.players.filter(q=>q.id!==p.id&&q.hp>0).sort((a,b)=>Math.hypot(b.x-p.x,b.y-p.y)-Math.hypot(a.x-p.x,a.y-p.y));
for(const q of others){const a=wrap(Math.atan2(q.y-p.y,q.x-p.x)-p.yaw),d=Math.hypot(q.x-p.x,q.y-p.y),depth=d*Math.cos(a);if(Math.abs(a)>fov*.85||depth<.15)continue;const xx=w/2+Math.tan(a)*proj,hh=proj/depth*.82,ww=hh*.45,top=horizon-hh*.48,team=q.team===0?'#54caff':'#ff796b';
for(let col=Math.max(0,Math.floor(xx-ww/2));col<Math.min(w,xx+ww/2);col+=2){if(depth>(z[col]||999)+.15)continue;const u=(col-xx)/ww;ctx.fillStyle=q.skin==='rogue'?'#535875':q.skin==='warden'?'#70806e':'#667c88';if(Math.abs(u)<.46)ctx.fillRect(col,top+hh*.27,2,hh*.43);ctx.fillStyle=team;if(Math.abs(u)<.31)ctx.fillRect(col,top+hh*.31,2,hh*.12);ctx.fillStyle='#d5b59d';if(Math.abs(u)<.22)ctx.fillRect(col,top+hh*.06,2,hh*.19);ctx.fillStyle='#17242c';if(Math.abs(u)>.08&&Math.abs(u)<.36)ctx.fillRect(col,top+hh*.7,2,hh*.3);}
const visible=depth<=(z[Math.max(0,Math.min(w-1,Math.floor(xx)))]||999)+.15;if(visible||(player.cheats.esp&&q.team!==player.team)){ctx.strokeStyle=team;ctx.lineWidth=1;ctx.strokeRect(xx-ww/2,top,ww,hh);ctx.fillStyle='#0009';ctx.fillRect(xx-ww/2,top-8,ww,4);ctx.fillStyle=team;ctx.fillRect(xx-ww/2,top-8,ww*q.hp/100,4);text(`${q.name} · ${q.hp}`,xx,top-14,Math.max(10,Math.min(13,w/60)),team,'center');}}
// ESP radar includes enemies outside the current field of view.
if(player.cheats.esp){const scale=Math.min(7,w/125),rw=20*scale,rh=12*scale;ctx.fillStyle='#051014c9';ctx.fillRect(14,94,rw,rh);map.forEach((row,iy)=>[...row].forEach((cell,ix)=>{if(cell==='1'){ctx.fillStyle='#526461';ctx.fillRect(14+ix*scale,94+iy*scale,scale,scale);}}));for(const q of state.players){if(q.hp<=0)continue;ctx.fillStyle=q.id===p.id?'#fff':q.team===0?'#55caff':'#ff796b';ctx.beginPath();ctx.arc(14+q.x*scale,94+q.y*scale,3,0,Math.PI*2);ctx.fill();}}
if(!dead){const bob=Math.sin(performance.now()/150)*(keys.size?3:0),gx=w*.60,gy=h*.77+bob+p.kick*100;ctx.fillStyle='#25323b';ctx.beginPath();ctx.moveTo(gx-25,h);ctx.lineTo(gx-17,gy);ctx.lineTo(gx+25,gy-35);ctx.lineTo(gx+46,gy-32);ctx.lineTo(gx+90,h);ctx.fill();ctx.fillStyle='#678089';ctx.fillRect(gx+3,gy-28,26,48);ctx.fillStyle='#c6ff47';ctx.fillRect(gx+10,gy-20,12,4);if(p.cooldown>.075){ctx.fillStyle='#ffe39a';ctx.beginPath();ctx.moveTo(gx+16,gy-70);ctx.lineTo(gx+37,gy-30);ctx.lineTo(gx-10,gy-40);ctx.fill();}ctx.strokeStyle='#c6ff47';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w/2-10,horizon);ctx.lineTo(w/2-3,horizon);ctx.moveTo(w/2+3,horizon);ctx.lineTo(w/2+10,horizon);ctx.moveTo(w/2,horizon-10);ctx.lineTo(w/2,horizon-3);ctx.moveTo(w/2,horizon+3);ctx.lineTo(w/2,horizon+10);ctx.stroke();if(performance.now()-(hitTimes.get(p.id)||-999)<130){text('×',w/2,horizon+5,22,'#fff','center');}}
ctx.fillStyle='#071113bb';ctx.fillRect(0,0,w,80);const alive=t=>state.players.filter(q=>q.team===t&&q.hp>0).length;text(`BLUE ${alive(0)}  |  ${state.score[0]} : ${state.score[1]}  |  ${alive(1)} RED`,w/2,28,Math.min(18,w/28),'#e7f1ed','center');text(`ROUND ${state.round}/5 · ${Math.ceil(state.timer)}s`,w/2,52,13,'#c6ff47','center');text(`P${index+1} / ${player.name}`,15,75,12);ctx.fillStyle='#08100dcc';ctx.fillRect(12,h-102,180,44);ctx.fillStyle='#37423d';ctx.fillRect(22,h-72,150,6);ctx.fillStyle=player.hp>30?'#c6ff47':'#ff786a';ctx.fillRect(22,h-72,150*player.hp/100,6);text(`HP ${player.hp}`,22,h-81,18);text(p.cheats.ammo?'∞ / INFINITE':p.reload>0?`RELOAD ${p.reload.toFixed(1)}`:`${p.ammo} / 30`,w-20,h-78,20,'#e7f1ed','right');
state.log.slice(-3).forEach((l,i)=>text(`${l.killer} → ${l.victim}`,w-15,105+i*19,11,l.team?'#ff9d91':'#7fd9ff','right'));
if(dead)text(`녹아웃 · ${p.id!==player.id?p.name+' 관전':'팀 전멸'} · V 전환`,w/2,h*.68,16,'#ff9d91','center');
if(state.state!=='PLAYING'){ctx.fillStyle='#050b0aaa';ctx.fillRect(0,h*.34,w,h*.22);text(state.state==='COUNTDOWN'?`ROUND ${state.round} · ${Math.ceil(state.timer)}`:state.message,w/2,h*.45,Math.min(29,w/24),'#c6ff47','center');}else if(state.message.includes('연장'))text(state.message,w/2,76,12,'#ffca70','center');ctx.restore();}
function frame(){const w=innerWidth,h=innerHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.fillStyle='#0a1013';ctx.fillRect(0,0,w,h);if(state&&map.length&&['COUNTDOWN','PLAYING','ROUND_END'].includes(state.state)){ids.forEach((id,i)=>{const p=state.players.find(p=>p.id===id);if(p)renderView(p,i*w/ids.length,0,w/ids.length,h,i);});if(ids.length===2){ctx.fillStyle='#c6ff47';ctx.fillRect(w/2-1,0,2,h);}}requestAnimationFrame(frame);}frame();
